# Generated by Django 3.2.3 on 2021-06-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0007_alter_postimages_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name': 'image', 'verbose_name_plural': 'image'},
        ),
    ]
