# Generated by Django 3.2.3 on 2021-06-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0009_alter_postimages_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
